INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('Ch.E','Chemical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('MME','Materials and Metallurgical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('CE','Civil Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('ME','Mechanical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('NAME','Naval Architecture and Marine Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('IPE','Industrial and Production Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('EEE','Electrical and Electronic Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('CSE','Computer Science and Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('BME','Biomedical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('Arch','Architecture');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('URP','Urban and Regional Planning Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('WRE','Water Resources Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('HUM','DEPARTMENT OF HUMANITIES');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('MATH','DEPARTMENT OF MATHEMATICS');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('PHYS','DEPARTMENT OF PHYSICS');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('CHEM','DEPARTMENT OF CHEMISTRY');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('GCE','DEPARTMENT OF GLASS AND CERAMIC Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('PMRE','PETROLEUM AND MINERAL RESOURCES Engineering');

