INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('ch.E','CHEMICAL ENGINEERING');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('MME','Materials and Metallurgical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('CE','Civil Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('ME','Mechanical Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('NAME','Naval Architecture and Marine Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('IPE','Industrial and Production Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('EEE','Electrical and Electronic Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('CSE','Computer Science and Engineering');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('BME','BIOMEDICAL ENGINEERING');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('Arch','Architecture');

INSERT INTO DEPARTMENTS (DEPT_ID,DEPT_NAME) VALUES('URP','Urban and Regional Planning');