-- password hash
CREATE OR REPLACE FUNCTION HASH_PASSWORD(PASSWORD IN VARCHAR) RETURN VARCHAR is
HASH VARCHAR(100);
BEGIN
HASH := dbms_crypto.hash(utl_raw.cast_to_raw(PASSWORD), dbms_crypto.HASH_MD5);
RETURN HASH;
END;



-- insert student after hashing password
CREATE OR REPLACE PROCEDURE INSERT_STUDENT
(ID IN NUMBER, NAME IN VARCHAR, DEPT IN VARCHAR, TERM IN VARCHAR ,INS IN VARCHAR,HALL_NAME IN VARCHAR,HALL_STATUS IN VARCHAR,MOBILE_NUMBER IN VARCHAR, ADDRESS IN VARCHAR, EMAIL IN VARCHAR, CONTACT_PERSON_NAME IN VARCHAR,CONTACT_PERSON_NUMBER IN VARCHAR,PASSWORD IN VARCHAR,PROFILE_PICTURE IN VARCHAR)
as
NEW_PASSWORD VARCHAR2(100);
BEGIN
NEW_PASSWORD := hash_password(password);
INSERT INTO STUDENTS 
(STUDENT_ID,STUDENT_NAME,DEPT_ID,TERM_ID,INS_ID,HALL_NAME,HALL_STATUS,MOBILE_NUMBER,ADDRESS,EMAIL,CONTACT_PERSON_NAME,CONTACT_PERSON_NUMBER,PSSWRD,PROFILE_PICTURE) 
VALUES
(ID,NAME,DEPT,TERM,INS,HALL_NAME,HALL_STATUS,MOBILE_NUMBER,ADDRESS,EMAIL,CONTACT_PERSON_NAME,CONTACT_PERSON_NUMBER,NEW_PASSWORD,PROFILE_PICTURE);
COMMIT;		
END;

	
